# 预训练的配置
# 数据集的设置基本不会改变
train_dataset: image_folder_pretrain
train_dataset_args: {
    root_path: /home/zit/21class/ZhengWang/Datasets/StanfordDog/Images,
    split: train,
    image_size: 84,
    patch_size: 26,
    patch_num: 36,
    augment: Crop_Resize,
    local_augment: local_Resize}

val_dataset: image_folder_pretrain
val_dataset_args: {
    root_path: /home/zit/21class/ZhengWang/Datasets/StanfordDog/Images,
    split: train,
    image_size: 84,
    patch_size: 26,
    patch_num: 36,
    local_augment: local_Crop}

fs_dataset: image_folder_pretrain
fs_dataset_args: {
    root_path: /home/zit/21class/ZhengWang/Datasets/StanfordDog/Images,
    split: test,
    image_size: 84,
    patch_size: 26,
    patch_num: 36,
    local_augment: local_Crop}



model: FusionNetForPretrain
model_args:
    globalNet: GlobalNetForPretrain
    globalNet_args: {
                        encoder: resnet12,
                        encoder_args: {},
                        classifier: 2LayerFC-classifier,
                        classifier_args: {n_classes: 70}
    }
    localNet: LocalNetForPretrain
    localNet_args: {
                       encoder: resnet12,
                       encoder_args: {},
                       classifier: 2LayerFC-classifier,
                       classifier_args: {n_classes: 70},
                       input_dim: 512,
                       head_num: 8,
                       feedforward_dim: 512,
                       batch_first: True
    }

# V4的模型完成预测需要加权系数，预训练时没有，所以就用V1的模型把，权重为0.5
fs_model: FusionNet
fs_model_args:
    globalNet: GlobalNet
    globalNet_args: {
                        encoder: resnet12,
                        encoder_args: {},
                        temp_learnable: False
    }
    localNet: LocalNet  # 之前写成V4了，V4和V1基本一样
    localNet_args: {
                       encoder: resnet12,
                       encoder_args: {},
                       classifier: localPatchClassifier,
                       classifier_args: {neighbor_k: 5},
                       input_dim: 512,
                       head_num: 8,
                       feedforward_dim: 512,
                       batch_first: True,
                       use_BGF: False,
                       temp_learnable: False
    }

eval_fs_epoch: 20
n_way: 5
n_query: 15
n_shots: [1, 5]    # 1-shot 和 5-shot 都要测试
ep_per_batch: 4

batch_size: 64
num_workers: 16

max_epoch: 600
optimizer: adam
optimizer_args: {lr: 0.001}

save_epoch: 5
visualize_datasets: false
