# 测试的配置文件中 仅 包含 测试数据集参数 和 小样本参数，
# 所以基本上不需要改动
dataset: image_folder_pretrain
dataset_args: {
    root_path: /home/zit/21class/ZhengWang/Datasets/StanfordCar/Images,
    split: test,
    image_size: 84,
    patch_size: 26,
    patch_num: 36,
    local_augment: local_Crop}

num_workers: 16

# 小样本参数
n_way: 5
n_query: 15
ep_per_batch: 4    # 最大取 4
n_batch: 150